### ISSUE TITLE
AttributeError: type object 'InferenceArguments' has no attribute 'current_culture'

### ISSUE THREAD

**Issue by krisbock** [Microsoft/AMLDataPrepDocs#26]
Running the getting-started.ipynb and encountering error when calling current_culture method in the second code cell.
==============================================================
gobike = dprep\
    .read_csv(
        path='https://dprepdata.blob.core.windows.net/demo/ford_gobike/2017-fordgobike-tripdata.csv',
        inference_arguments=dprep.InferenceArguments.current_culture()
    )
gobike.head(5)
===============================================================
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8c71071a05f6> in <module>
      2     .read_csv(
      3         path='https://dprepdata.blob.core.windows.net/demo/ford_gobike/2017-fordgobike-tripdata.csv',
----> 4         inference_arguments=dprep.InferenceArguments.current_culture()
      5     )
      6 gobike.head(5)

AttributeError: type object 'InferenceArguments' has no attribute 'current_culture'

Running azureml.dataprep version 0.5.1.

**Comment by yikei** [comment]
Thank you for your comment. Currently, the notebooks in this repo are outdated and are for Version 0.4.0. We are in the process of updating these notebooks for the latest SDK version.

**Comment by yikei** [comment]
@krisbock We have updated our notebooks, so they are now compatible with the Data Prep SDK version 0.5.0 and above. Please let us know if you run into any other issues. We welcome any questions or feedback. Thanks!
