### ISSUE TITLE
 profile.columns['District'].histogram returns list

### ISSUE THREAD

**Issue by jim-brown** [microsoft/AMLDataPrepDocs#56]
AMLDataPrepDocs/how-to-guides/data-profile.ipynb

This notebook contains the following call which only returns a list of HistogramBucket objects:

profile.columns['District'].histogram

RETURNS:
[HistogramBucket(lower_bound=1.0, upper_bound=1.1, count=670289.0837049744),
 HistogramBucket(lower_bound=1.1, upper_bound=1.2, count=4374.664296025061),
 HistogramBucket(lower_bound=1.2, upper_bound=1.3, count=1324.4878810594091),
 HistogramBucket(lower_bound=1.3, upper_bound=1.4, count=1324.487881059642),
 HistogramBucket(lower_bound=1.4, upper_bound=1.5, count=1324.4878810594091),
 HistogramBucket(lower_bound=1.5, upper_bound=1.6, count=1324.4878810594091),
 HistogramBucket(lower_bound=1.6, upper_bound=1.7000000000000002, count=1324.4878810595255),
 HistogramBucket(lower_bound=1.7000000000000002, upper_bound=1.8, count=1324.4878810594091),
 HistogramBucket(lower_bound=1.8, upper_bound=1.9, count=1324.4878810595255),
 HistogramBucket(lower_bound=1.9, upper_bound=2.0, count=774708.8368315842)]

When running the notebook, I expected a histogram to be displayed. There does not seem to be a way to actually display the histogram.

**Comment by yikei** [comment]
Hi @jim-brown , the Data Prep SDK does not provide any visualization capabilities. Please use a separate viz library to display a chart (by providing the histogram details returned from the data profile).
